apiVersion: v1
kind: Service
metadata:
  name: {{ include "traditional-saju.fullname" . }}
  labels:
    {{- include "traditional-saju.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "traditional-saju.app.selectorLabels" . | nindent 4 }}
