apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traditional-saju.fullname" . }}-config
  labels:
    {{- include "traditional-saju.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}
