{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traditional-saju.databaseSecretName" . }}
  labels:
    {{- include "traditional-saju.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- $username := .Values.database.username }}
  {{- $password := .Values.database.password }}
  {{- $host := .Values.database.host }}
  {{- $port := .Values.database.port | default 5432 | int }}
  {{- $dbName := .Values.database.dbName }}
  {{- $sslMode := .Values.database.sslMode | default "disable" }}

  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s?schema=public&sslmode=%s" $username $password $host $port $dbName $sslMode | b64enc | quote }}
{{- end }}
